package school.magiccodex.client;
import java.util.function.Function;import net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents;import net.fabricmc.fabric.api.client.networking.v1.*;import net.fabricmc.fabric.api.networking.v1.PayloadTypeRegistry;import net.minecraft.network.*;import net.minecraft.network.codec.PacketCodec;import net.minecraft.network.packet.CustomPayload;import net.minecraft.util.*;import school.magiccodex.protocol.ShopProtocol;import school.magiccodex.protocol.ShopProtocol.*;
public final class ShopClient {
 private static long sequence,waiting,deadline;private static ShopScreen owner;
 private interface Bytes{byte[] bytes();}
 public record Query(byte[]bytes)implements CustomPayload,Bytes{public static final Id<Query>ID=new Id<>(Identifier.of(ShopProtocol.REQUEST));public static final PacketCodec<RegistryByteBuf,Query>CODEC=codec(Query::new);public Id<Query>getId(){return ID;}}
 public record Reply(byte[]bytes)implements CustomPayload,Bytes{public static final Id<Reply>ID=new Id<>(Identifier.of(ShopProtocol.RESPONSE));public static final PacketCodec<RegistryByteBuf,Reply>CODEC=codec(Reply::new);public Id<Reply>getId(){return ID;}}
 private static <T extends Bytes>PacketCodec<RegistryByteBuf,T>codec(Function<byte[],T>make){return new PacketCodec<>(){public T decode(RegistryByteBuf b){int n=b.readableBytes();if(n<4||n>ShopProtocol.MAX_BYTES){b.skipBytes(n);return make.apply(new byte[0]);}byte[] bytes=new byte[n];b.readBytes(bytes);return make.apply(bytes);}public void encode(RegistryByteBuf b,T v){b.writeBytes(v.bytes());}};}
 public static void initialize(){PayloadTypeRegistry.playC2S().register(Query.ID,Query.CODEC);PayloadTypeRegistry.playS2C().register(Reply.ID,Reply.CODEC);ClientPlayNetworking.registerGlobalReceiver(Reply.ID,(p,c)->{try{var r=ShopProtocol.response(p.bytes());c.client().execute(()->{if(r.sequence()==0){if(c.client().player==null)return;MagicCodexClient.dismiss();var screen=new ShopScreen();c.client().setScreen(screen);screen.receive(r);return;}if(r.sequence()!=waiting)return;var screen=owner;waiting=0;owner=null;if(screen!=null&&c.client().currentScreen==screen)screen.receive(r);});}catch(IllegalArgumentException ignored){}});ClientPlayConnectionEvents.JOIN.register((h,s,c)->reset());ClientPlayConnectionEvents.DISCONNECT.register((h,c)->reset());ClientTickEvents.END_CLIENT_TICK.register(c->{if(waiting!=0&&Util.getMeasuringTimeMs()>deadline){var s=owner;waiting=0;owner=null;if(s!=null)s.failed("응답이 늦습니다. 우편/인벤토리와 거래 상태를 확인해 주세요.");}});}
 private static void reset(){waiting=sequence=deadline=0;owner=null;}
 static boolean request(ShopScreen s,Request r){if(waiting!=0||!ClientPlayNetworking.canSend(Query.ID))return false;long seq=++sequence;if(r.action()!=ShopProtocol.CLOSE){waiting=seq;deadline=Util.getMeasuringTimeMs()+12000;owner=s;}ClientPlayNetworking.send(new Query(ShopProtocol.encode(new Request(r.action(),seq,r.session(),r.shop(),r.revision(),r.product(),r.quantity(),r.operation(),r.search()))));return true;}
 static void detach(ShopScreen s){if(owner==s)owner=null;}
}
