package school.magiccodex.client;

import java.util.*;

/** Authored, offline-mixed spell cues. Generated from spell-audio-200-v1/catalog.json. */
public final class SpellCastSounds {
    public record Cue(String id,String label,String event,long durationMillis,float volume) {}
    private static final Map<String,Cue> IDS;
    private static final Map<String,Cue> NAMES;
    static {
        var ids=new LinkedHashMap<String,Cue>();var names=new HashMap<String,Cue>();
        add(ids,names,new Cue("wind_basket","바람 바구니","cast.wind_basket",1276L,.65f));
        add(ids,names,new Cue("feather_step","깃털 걸음","cast.feather_step",1276L,.65f));
        add(ids,names,new Cue("harvest_wind","수확의 바람","cast.harvest_wind",1276L,.65f));
        add(ids,names,new Cue("wind_push","바람 밀치기","cast.wind_push",1276L,.65f));
        add(ids,names,new Cue("light_leap","가벼운 도약","cast.light_leap",1276L,.65f));
        add(ids,names,new Cue("flight","비행","cast.flight",1816L,.65f));
        add(ids,names,new Cue("far_touch","손길 너머","cast.far_touch",1816L,.65f));
        add(ids,names,new Cue("aerial_haul","공중 운반","cast.aerial_haul",1816L,.65f));
        add(ids,names,new Cue("wind_message","바람의 전언","cast.wind_message",1816L,.65f));
        add(ids,names,new Cue("storm_command","폭풍의 지휘","cast.storm_command",2656L,.65f));
        add(ids,names,new Cue("wind_vault","바람의 금고","cast.wind_vault",2656L,.65f));
        add(ids,names,new Cue("vacuum_cleave","진공 절단","cast.vacuum_cleave",2356L,.65f));
        add(ids,names,new Cue("wind_grooming","바람 털빗","cast.wind_grooming",1276L,.65f));
        add(ids,names,new Cue("dust_duster","먼지떨이","cast.dust_duster",1276L,.65f));
        add(ids,names,new Cue("leaf_cleanup","잎새 청소","cast.leaf_cleanup",1276L,.65f));
        add(ids,names,new Cue("gale_dash","돌풍 질주","cast.gale_dash",1456L,.65f));
        add(ids,names,new Cue("feather_rustle","깃털 털기","cast.feather_rustle",1456L,.65f));
        add(ids,names,new Cue("cross_breeze","엇바람","cast.cross_breeze",1456L,.65f));
        add(ids,names,new Cue("returning_blade","되돌이 칼날","cast.returning_blade",1636L,.65f));
        add(ids,names,new Cue("pressure_press","풍압 누르기","cast.pressure_press",1636L,.65f));
        add(ids,names,new Cue("returning_wind","되받는 바람","cast.returning_wind",1816L,.65f));
        add(ids,names,new Cue("wind_decoy","바람 미끼","cast.wind_decoy",1816L,.65f));
        add(ids,names,new Cue("air_step","허공 디딤","cast.air_step",1816L,.65f));
        add(ids,names,new Cue("weightless_zone","무중력 지대","cast.weightless_zone",1996L,.65f));
        add(ids,names,new Cue("lightning_needle","벼락 바늘","cast.lightning_needle",1996L,.65f));
        add(ids,names,new Cue("air_stacking","허공 쌓기","cast.air_stacking",1996L,.65f));
        add(ids,names,new Cue("descent_command","낙하 명령","cast.descent_command",2176L,.65f));
        add(ids,names,new Cue("arrested_orbit","정지 궤도","cast.arrested_orbit",2176L,.65f));
        add(ids,names,new Cue("crossfire","교차 사격","cast.crossfire",2176L,.65f));
        add(ids,names,new Cue("trajectory_acceleration","궤도 가속","cast.trajectory_acceleration",2356L,.65f));
        add(ids,names,new Cue("resonant_arrow","공명하는 화살","cast.resonant_arrow",2356L,.65f));
        add(ids,names,new Cue("pressure_rupture","대기압 파열","cast.pressure_rupture",2536L,.65f));
        add(ids,names,new Cue("storm_crown","폭풍의 왕관","cast.storm_crown",2716L,.65f));
        add(ids,names,new Cue("hearth_touch","손끝 화로","cast.hearth_touch",1276L,.65f));
        add(ids,names,new Cue("ember_bolt","불씨 탄환","cast.ember_bolt",1276L,.65f));
        add(ids,names,new Cue("rekindle","다시 타오르는 불","cast.rekindle",1276L,.65f));
        add(ids,names,new Cue("flame_forging","불꽃 단조","cast.flame_forging",1816L,.65f));
        add(ids,names,new Cue("ember_trap","잿불 덫","cast.ember_trap",1816L,.65f));
        add(ids,names,new Cue("fire_curtain","불의 장막","cast.fire_curtain",1816L,.65f));
        add(ids,names,new Cue("phoenix_oath","불사조의 서약","cast.phoenix_oath",2356L,.65f));
        add(ids,names,new Cue("living_furnace","살아 있는 화로","cast.living_furnace",2356L,.65f));
        add(ids,names,new Cue("falling_star","낙성","cast.falling_star",2356L,.65f));
        add(ids,names,new Cue("palm_fireworks","손바닥 폭죽","cast.palm_fireworks",1276L,.65f));
        add(ids,names,new Cue("wick_trimming","심지 줄이기","cast.wick_trimming",1276L,.65f));
        add(ids,names,new Cue("glass_firing","유리 소성","cast.glass_firing",1276L,.65f));
        add(ids,names,new Cue("charcoal_conversion","숯불 전환","cast.charcoal_conversion",1456L,.65f));
        add(ids,names,new Cue("sponge_drying","스펀지 말리기","cast.sponge_drying",1456L,.65f));
        add(ids,names,new Cue("flame_lash","화염 채찍","cast.flame_lash",1636L,.65f));
        add(ids,names,new Cue("cinder_detonation","잔불 폭발","cast.cinder_detonation",1636L,.65f));
        add(ids,names,new Cue("flame_footprints","불꽃 발자국","cast.flame_footprints",1636L,.65f));
        add(ids,names,new Cue("boiling_armor","끓는 갑주","cast.boiling_armor",1636L,.65f));
        add(ids,names,new Cue("kiln_breath","가마 숨결","cast.kiln_breath",2116L,.65f));
        add(ids,names,new Cue("glaze_coating","유약 입히기","cast.glaze_coating",1816L,.65f));
        add(ids,names,new Cue("ash_brand","재의 낙인","cast.ash_brand",1996L,.65f));
        add(ids,names,new Cue("explosive_wedge","폭발 쐐기","cast.explosive_wedge",1996L,.65f));
        add(ids,names,new Cue("fireproof_film","불연 피막","cast.fireproof_film",1996L,.65f));
        add(ids,names,new Cue("flame_leap","불꽃 도약","cast.flame_leap",2476L,.65f));
        add(ids,names,new Cue("heat_recovery","열량 회수","cast.heat_recovery",2176L,.65f));
        add(ids,names,new Cue("firebird_hunt","불새의 사냥","cast.firebird_hunt",2176L,.65f));
        add(ids,names,new Cue("lava_suture","용암 봉합","cast.lava_suture",2356L,.65f));
        add(ids,names,new Cue("flame_sword_dance","화염 검무","cast.flame_sword_dance",2356L,.65f));
        add(ids,names,new Cue("incandescent_break","백열 단절","cast.incandescent_break",2536L,.65f));
        add(ids,names,new Cue("blue_bonfire","푸른 화톳불","cast.blue_bonfire",2536L,.65f));
        add(ids,names,new Cue("crimson_heart","홍련의 심장","cast.crimson_heart",2716L,.65f));
        add(ids,names,new Cue("crimson_breath","홍염의 숨","cast.crimson_breath",3016L,.65f));
        add(ids,names,new Cue("water_breath","물결 숨결","cast.water_breath",1576L,.65f));
        add(ids,names,new Cue("tide_stride","물살 타기","cast.tide_stride",1276L,.65f));
        add(ids,names,new Cue("water_bolt","물방울 탄환","cast.water_bolt",1276L,.65f));
        add(ids,names,new Cue("quench","불길 씻기","cast.quench",1276L,.65f));
        add(ids,names,new Cue("purifying_wave","정화의 물결","cast.purifying_wave",1816L,.65f));
        add(ids,names,new Cue("ice_bridge","얼음 다리","cast.ice_bridge",1816L,.65f));
        add(ids,names,new Cue("water_mirror","수면의 거울","cast.water_mirror",2116L,.65f));
        add(ids,names,new Cue("spring_unseal","수맥 개방","cast.spring_unseal",1816L,.65f));
        add(ids,names,new Cue("water_elemental","물의 정령 소환","cast.water_elemental",2656L,.65f));
        add(ids,names,new Cue("eternal_ice_prison","만년빙옥","cast.eternal_ice_prison",2356L,.65f));
        add(ids,names,new Cue("cauldron_fill","가마솥 채우기","cast.cauldron_fill",1276L,.65f));
        add(ids,names,new Cue("dye_rinse","염색 씻기","cast.dye_rinse",1276L,.65f));
        add(ids,names,new Cue("moist_farmland","촉촉한 밭","cast.moist_farmland",1276L,.65f));
        add(ids,names,new Cue("wash_letters","글씨 씻기","cast.wash_letters",1276L,.65f));
        add(ids,names,new Cue("handful_of_snow","눈 한 줌","cast.handful_of_snow",1276L,.65f));
        add(ids,names,new Cue("fish_lure","물고기 유인","cast.fish_lure",1456L,.65f));
        add(ids,names,new Cue("dew_gathering","이슬 모으기","cast.dew_gathering",1456L,.65f));
        add(ids,names,new Cue("quiet_mooring","잔잔한 정박","cast.quiet_mooring",1456L,.65f));
        add(ids,names,new Cue("frost_rupture","서리 파열","cast.frost_rupture",1636L,.65f));
        add(ids,names,new Cue("wet_footprints","젖은 발자국","cast.wet_footprints",1636L,.65f));
        add(ids,names,new Cue("pressure_weight","수압추","cast.pressure_weight",1636L,.65f));
        add(ids,names,new Cue("cold_storage","냉장 손길","cast.cold_storage",1816L,.65f));
        add(ids,names,new Cue("current_sorting","물살 분류","cast.current_sorting",1816L,.65f));
        add(ids,names,new Cue("dampen_powder","화약 적시기","cast.dampen_powder",1996L,.65f));
        add(ids,names,new Cue("potion_mist","약액 분무","cast.potion_mist",1996L,.65f));
        add(ids,names,new Cue("waterwheel_shield","물레 방패","cast.waterwheel_shield",1996L,.65f));
        add(ids,names,new Cue("liquid_barrier","액체 차단","cast.liquid_barrier",2176L,.65f));
        add(ids,names,new Cue("water_rebound","수면 탄성","cast.water_rebound",2176L,.65f));
        add(ids,names,new Cue("tidal_wave","해일","cast.tidal_wave",2656L,.65f));
        add(ids,names,new Cue("life_distribution","생명의 분배","cast.life_distribution",2536L,.65f));
        add(ids,names,new Cue("thaw_pulse","해빙의 맥동","cast.thaw_pulse",2536L,.65f));
        add(ids,names,new Cue("abyssal_pressure","심해의 압력","cast.abyssal_pressure",2716L,.65f));
        add(ids,names,new Cue("verdant_touch","풍요의 손길","cast.verdant_touch",1276L,.65f));
        add(ids,names,new Cue("ore_whisper","땅의 속삭임","cast.ore_whisper",1276L,.65f));
        add(ids,names,new Cue("pebble_toss","조약돌 던지기","cast.pebble_toss",1276L,.65f));
        add(ids,names,new Cue("miners_rhythm","광부의 박자","cast.miners_rhythm",1276L,.65f));
        add(ids,names,new Cue("earth_shaping","대지 성형","cast.earth_shaping",1816L,.65f));
        add(ids,names,new Cue("stone_wall","석벽","cast.stone_wall",1816L,.65f));
        add(ids,names,new Cue("vine_ladder","덩굴 사다리","cast.vine_ladder",1816L,.65f));
        add(ids,names,new Cue("earth_elemental","땅의 정령 소환","cast.earth_elemental",2656L,.65f));
        add(ids,names,new Cue("earthquake","지진","cast.earthquake",2656L,.65f));
        add(ids,names,new Cue("climate_control","기후 통제","cast.climate_control",2656L,.65f));
        add(ids,names,new Cue("moss_coating","이끼 입히기","cast.moss_coating",1276L,.65f));
        add(ids,names,new Cue("grass_sprouting","잔디 돋우기","cast.grass_sprouting",1276L,.65f));
        add(ids,names,new Cue("seed_row","씨앗 줄심기","cast.seed_row",1456L,.65f));
        add(ids,names,new Cue("bee_calm","벌떼 달래기","cast.bee_calm",1456L,.65f));
        add(ids,names,new Cue("flint_sorting","돌 고르기","cast.flint_sorting",1456L,.65f));
        add(ids,names,new Cue("bark_peeling","껍질 벗기기","cast.bark_peeling",1456L,.65f));
        add(ids,names,new Cue("thorn_armor","가시 갑옷","cast.thorn_armor",1636L,.65f));
        add(ids,names,new Cue("compost_return","퇴비 환원","cast.compost_return",1636L,.65f));
        add(ids,names,new Cue("thorn_seeds","가시 씨앗","cast.thorn_seeds",1636L,.65f));
        add(ids,names,new Cue("pollen_matchmaking","꽃가루 중매","cast.pollen_matchmaking",1816L,.65f));
        add(ids,names,new Cue("automatic_supply","자동 보급","cast.automatic_supply",1816L,.65f));
        add(ids,names,new Cue("earth_anchor","대지의 닻","cast.earth_anchor",1996L,.65f));
        add(ids,names,new Cue("weathering_touch","풍화의 손길","cast.weathering_touch",1996L,.65f));
        add(ids,names,new Cue("dormant_seed","동면의 씨앗","cast.dormant_seed",1996L,.65f));
        add(ids,names,new Cue("counterweight","반격의 무게추","cast.counterweight",1996L,.65f));
        add(ids,names,new Cue("vein_fracture","광맥 파쇄","cast.vein_fracture",2176L,.65f));
        add(ids,names,new Cue("iron_carapace","철의 외피","cast.iron_carapace",2176L,.65f));
        add(ids,names,new Cue("material_exchange","자재 치환","cast.material_exchange",2176L,.65f));
        add(ids,names,new Cue("remembering_field","기억하는 밭","cast.remembering_field",2176L,.65f));
        add(ids,names,new Cue("little_giant","작은 거인","cast.little_giant",2656L,.65f));
        add(ids,names,new Cue("spring_ground","용수철 지반","cast.spring_ground",2356L,.65f));
        add(ids,names,new Cue("mountain_back","산맥의 등","cast.mountain_back",2536L,.65f));
        add(ids,names,new Cue("earth_embrace","대지의 품","cast.earth_embrace",2536L,.65f));
        add(ids,names,new Cue("forest_throne","숲의 왕좌","cast.forest_throne",2716L,.65f));
        add(ids,names,new Cue("primordial_stone","원초의 돌","cast.primordial_stone",2716L,.65f));
        add(ids,names,new Cue("guiding_star","길잡이 별","cast.guiding_star",1276L,.65f));
        add(ids,names,new Cue("minor_heal","작은 치유","cast.minor_heal",1276L,.65f));
        add(ids,names,new Cue("light_mark","빛의 낙인","cast.light_mark",1276L,.65f));
        add(ids,names,new Cue("spatial_leap","공간 도약","cast.spatial_leap",2116L,.65f));
        add(ids,names,new Cue("luminous_archive","빛의 서고","cast.luminous_archive",1816L,.65f));
        add(ids,names,new Cue("true_sight","진실의 눈","cast.true_sight",1816L,.65f));
        add(ids,names,new Cue("protective_ward","보호 결계","cast.protective_ward",1816L,.65f));
        add(ids,names,new Cue("constellation_blessing","성좌의 가호","cast.constellation_blessing",2656L,.65f));
        add(ids,names,new Cue("arcane_imprint","마력 각인","cast.arcane_imprint",2356L,.65f));
        add(ids,names,new Cue("dawn_ritual","여명의 의식","cast.dawn_ritual",2656L,.65f));
        add(ids,names,new Cue("firefly_mark","반딧불 표식","cast.firefly_mark",1276L,.65f));
        add(ids,names,new Cue("rainbow_collar","무지개 목줄","cast.rainbow_collar",1276L,.65f));
        add(ids,names,new Cue("comforting_light","위로의 빛","cast.comforting_light",1456L,.65f));
        add(ids,names,new Cue("sun_drying","햇살 말림","cast.sun_drying",1456L,.65f));
        add(ids,names,new Cue("luminous_copy","빛의 필사","cast.luminous_copy",1456L,.65f));
        add(ids,names,new Cue("exorcism_flash","퇴마의 섬광","cast.exorcism_flash",1636L,.65f));
        add(ids,names,new Cue("arcane_mending","마력 봉합","cast.arcane_mending",1636L,.65f));
        add(ids,names,new Cue("guiding_fletching","유도 깃","cast.guiding_fletching",1636L,.65f));
        add(ids,names,new Cue("sharing_table","나눔 식탁","cast.sharing_table",1636L,.65f));
        add(ids,names,new Cue("summons_letter","소환장","cast.summons_letter",1816L,.65f));
        add(ids,names,new Cue("starlight_survey","별빛 측량","cast.starlight_survey",1816L,.65f));
        add(ids,names,new Cue("luminous_handover","빛의 교대","cast.luminous_handover",1996L,.65f));
        add(ids,names,new Cue("mana_conduit","마력 전선","cast.mana_conduit",2176L,.65f));
        add(ids,names,new Cue("companion_return","동행 귀환","cast.companion_return",2656L,.65f));
        add(ids,names,new Cue("merciful_arrow","자비의 화살","cast.merciful_arrow",2356L,.65f));
        add(ids,names,new Cue("mana_deposit","마력 예금","cast.mana_deposit",2356L,.65f));
        add(ids,names,new Cue("flawless_moment","무결의 순간","cast.flawless_moment",2536L,.65f));
        add(ids,names,new Cue("guardian_oath","수호자의 서약","cast.guardian_oath",2536L,.65f));
        add(ids,names,new Cue("experience_exchange","경험의 환전","cast.experience_exchange",2536L,.65f));
        add(ids,names,new Cue("solar_judgment","태양의 심판","cast.solar_judgment",3016L,.65f));
        add(ids,names,new Cue("white_night_sanctuary","백야의 성역","cast.white_night_sanctuary",2716L,.65f));
        add(ids,names,new Cue("starlight_reprise","별빛 재현","cast.starlight_reprise",2716L,.65f));
        add(ids,names,new Cue("constellation_emissary","성좌의 대리인","cast.constellation_emissary",3016L,.65f));
        add(ids,names,new Cue("night_sight","밤눈","cast.night_sight",1276L,.65f));
        add(ids,names,new Cue("shadow_bind","그림자 매듭","cast.shadow_bind",1276L,.65f));
        add(ids,names,new Cue("faint_veil","옅은 은신","cast.faint_veil",1276L,.65f));
        add(ids,names,new Cue("shadow_double","그림자 분신","cast.shadow_double",1816L,.65f));
        add(ids,names,new Cue("echo_reading","잔향 읽기","cast.echo_reading",1816L,.65f));
        add(ids,names,new Cue("sealing_thread","봉인의 실","cast.sealing_thread",1816L,.65f));
        add(ids,names,new Cue("afterlife_gate","사후세계의 문","cast.afterlife_gate",2656L,.65f));
        add(ids,names,new Cue("shadow_exchange","그림자 교환","cast.shadow_exchange",2356L,.65f));
        add(ids,names,new Cue("forbidden_contract","금서의 계약","cast.forbidden_contract",2356L,.65f));
        add(ids,names,new Cue("ink_fingertip","먹물 손끝","cast.ink_fingertip",1276L,.65f));
        add(ids,names,new Cue("drowsiness","졸음","cast.drowsiness",1456L,.65f));
        add(ids,names,new Cue("misfortune_whisper","불운의 속삭임","cast.misfortune_whisper",1456L,.65f));
        add(ids,names,new Cue("shadow_nail","그림자 못","cast.shadow_nail",1456L,.65f));
        add(ids,names,new Cue("night_lullaby","밤의 자장가","cast.night_lullaby",1456L,.65f));
        add(ids,names,new Cue("life_siphon","생명 갈취","cast.life_siphon",1636L,.65f));
        add(ids,names,new Cue("hungry_shadow","굶주린 그림자","cast.hungry_shadow",1636L,.65f));
        add(ids,names,new Cue("loosen_grasp","손아귀 풀기","cast.loosen_grasp",1636L,.65f));
        add(ids,names,new Cue("shadow_tracking","그림자 추적","cast.shadow_tracking",1636L,.65f));
        add(ids,names,new Cue("healing_seal","회복 봉인","cast.healing_seal",1816L,.65f));
        add(ids,names,new Cue("shadow_scales","어둠의 저울","cast.shadow_scales",1816L,.65f));
        add(ids,names,new Cue("curse_transfer","저주의 전가","cast.curse_transfer",1996L,.65f));
        add(ids,names,new Cue("warning_thread","경고의 실","cast.warning_thread",1996L,.65f));
        add(ids,names,new Cue("final_knot","끝매듭","cast.final_knot",1996L,.65f));
        add(ids,names,new Cue("discord","불화","cast.discord",2176L,.65f));
        add(ids,names,new Cue("wound_accounting","상처 회계","cast.wound_accounting",2176L,.65f));
        add(ids,names,new Cue("inverted_offering","뒤집힌 공물","cast.inverted_offering",2176L,.65f));
        add(ids,names,new Cue("night_chain","밤의 사슬","cast.night_chain",2356L,.65f));
        add(ids,names,new Cue("ghost_tool","유령 도구","cast.ghost_tool",2356L,.65f));
        add(ids,names,new Cue("bell_of_fear","공포의 종","cast.bell_of_fear",2656L,.65f));
        add(ids,names,new Cue("pain_deferral","고통 유예","cast.pain_deferral",2536L,.65f));
        add(ids,names,new Cue("eclipse_eye","월식의 눈","cast.eclipse_eye",2536L,.65f));
        add(ids,names,new Cue("death_ledger","죽음의 장부","cast.death_ledger",2536L,.65f));
        add(ids,names,new Cue("black_harvest","검은 수확","cast.black_harvest",2716L,.65f));
        add(ids,names,new Cue("void_maw","공허의 입","cast.void_maw",3016L,.65f));
        add(ids,names,new Cue("twilight_bargain","황혼의 거래","cast.twilight_bargain",2716L,.65f));
        IDS=Collections.unmodifiableMap(ids);NAMES=Map.copyOf(names);
    }
    private SpellCastSounds() {}
    private static void add(Map<String,Cue> ids,Map<String,Cue> names,Cue cue){
        if(ids.put(cue.id(),cue)!=null || names.put(normalize(cue.label()),cue)!=null)throw new IllegalStateException("Duplicate spell sound identity");
    }
    public static Cue byId(String id){return IDS.get(id);}
    public static Collection<Cue> values(){return IDS.values();}
    public static Cue find(String value){String key=normalize(value);var cue=IDS.get(key);return cue!=null?cue:NAMES.get(key);}
    private static String normalize(String value){return value==null?"":value.replaceAll("\\s+", "").toLowerCase(Locale.ROOT);}
}
