package school.magiccodex.paper;
import java.nio.file.*;
import java.sql.*;
import java.util.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;
import school.magiccodex.protocol.*;

class QuestRevisionTest {
    @TempDir Path dir;
    private QuestDefinition q(){var q=QuestStoreTest.quest("patrol",false);return new QuestDefinition(q.id(),q.title(),q.description(),q.permission(),false,true,q.objectives(),q.rewardLabel(),q.commands(),q.items(),"C",3,0,100,5);}
    private void finish(QuestStore s,UUID p,QuestDefinition q,long n)throws Exception{s.advance(p,QuestDefinition.Type.KILL,"ZOMBIE","wild","world",10,n);var e=s.reserve(p,q.id(),"once",n);assertNotNull(e);s.finish(p,e,true);assertThrows(SQLException.class,()->s.finish(p,e,true));}
    @Test void repeatQuotaSurvivesAbandonAndRestart()throws Exception{UUID p=UUID.randomUUID();long n=System.currentTimeMillis();var q=q();Path file=dir.resolve("q.db");try(var s=new QuestStore(QuestStoreTest.SQLITE,file)){assertTrue(s.accept(p,q,n));finish(s,p,q,n);assertTrue(s.accept(p,q,n));assertTrue(s.abandon(p,q.id(),n));assertEquals(1,s.entries(p).getFirst().completions());}try(var s=new QuestStore(QuestStoreTest.SQLITE,file)){assertTrue(s.accept(p,q,n));assertEquals(0,s.entries(p).getFirst().progress()[0]);finish(s,p,q,n);assertTrue(s.accept(p,q,n));finish(s,p,q,n);assertEquals(3,s.entries(p).getFirst().completions());assertFalse(s.accept(p,q,n));}}
    @Test void snapshotOldFormatAndSchemaMigration()throws Exception{var q=QuestStoreTest.quest("old",false);byte[] data=Base64.getDecoder().decode(q.encode());String old=Base64.getEncoder().encodeToString(Arrays.copyOf(data,data.length-27));assertEquals(q,QuestDefinition.decode(old));Path file=dir.resolve("old.db");try(var c=QuestStoreTest.SQLITE.connect(file);var s=c.createStatement()){s.execute("CREATE TABLE codex_quest_progress(player VARCHAR(36),quest VARCHAR(48),cycle VARCHAR(16),definition TEXT,status VARCHAR(16),progress VARCHAR(128),token VARCHAR(36),updated BIGINT,PRIMARY KEY(player,quest,cycle))");try(var insert=c.prepareStatement("INSERT INTO codex_quest_progress VALUES(?,?,'once',?,'claimed','10','',0)")){insert.setString(1,new UUID(0,1).toString());insert.setString(2,"old");insert.setString(3,old);insert.executeUpdate();}}try(var s=new QuestStore(QuestStoreTest.SQLITE,file)){assertEquals(1,s.entries(new UUID(0,1)).getFirst().completions());assertFalse(s.accept(new UUID(0,1),q,System.currentTimeMillis()));}}
    @Test void timedReleaseAndManualClose()throws Exception{var q=q();long now=System.currentTimeMillis();try(var s=new QuestStore(QuestStoreTest.SQLITE,dir.resolve("q.db"))){s.seed(Map.of(q.id(),q));var result=s.release(List.of(q.id()),now+60000,0,true).get(q.id());assertFalse(s.accept(UUID.randomUUID(),result,now));assertTrue(s.accept(UUID.randomUUID(),result,now+60000));assertFalse(s.release(List.of(q.id()),now,0,false).get(q.id()).available(now));}}
    @Test void editorCompareAndSwapProtectsOtherAdmins()throws Exception{var q=q();try(var s=new QuestStore(QuestStoreTest.SQLITE,dir.resolve("q.db"))){assertTrue(s.edit(q.id(),"",q));assertFalse(s.edit(q.id(),"",q));String rev=QuestStore.fingerprint(q);assertTrue(s.edit(q.id(),rev,q.release(123,false)));assertFalse(s.edit(q.id(),rev,null));assertNotNull(s.catalog().get(q.id()));}}
    @Test void houseScoreGoesToExistingScoreOnce()throws Exception{Path file=dir.resolve("school.db");String token=UUID.randomUUID().toString();try(var s=new SchoolStore(file)){assertTrue(s.questReward(token,2,50));assertFalse(s.questReward(token,2,50));assertEquals(List.of(0L,0L,50L,0L),s.snapshot().scores());assertTrue(s.snapshot().records().isEmpty());}try(var s=new SchoolStore(file)){assertFalse(s.questReward(token,2,50));assertEquals(50,s.snapshot().scores().get(2));}}
    @Test void newWireFieldsAndAdminRoundTrip(){var q=q();assertEquals(q,QuestDefinition.decode(q.encode()));var card=new QuestProtocol.Card("q","title","story","기숙사 점수 +5\n돈 +100","available",List.of(new QuestProtocol.Goal("처치",0,10)),"A",2,3);var r=new QuestProtocol.Response(false,1,8,"",List.of(card));assertEquals(r,QuestProtocol.response(QuestProtocol.encode(r)));var req=new QuestProtocol.Request(0,1,"",2);assertEquals(req,QuestProtocol.request(QuestProtocol.encode(req)));var a=new QuestAdminProtocol.Request(2,"q","abc",Map.of("description","첫 줄\n두 번째 줄","reward.commands","give {player} emerald 1"));assertEquals(a,QuestAdminProtocol.request(QuestAdminProtocol.encode(a)));assertThrows(IllegalArgumentException.class,()->QuestAdminProtocol.request(QuestAdminProtocol.encode(new QuestAdminProtocol.Request(9,"q","",Map.of()))));}
}
