package school.magiccodex.paper;
import static org.junit.jupiter.api.Assertions.*;
import java.nio.file.*;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;
import school.magiccodex.database.DatabaseSettings;import school.magiccodex.protocol.ShopProtocol;
class ShopStoreTest {
 @TempDir Path dir;ShopStore store;UUID owner=UUID.randomUUID();String product;
 @BeforeEach void setup()throws Exception{store=new ShopStore(DatabaseSettings.load(dir.resolve("missing.properties")),dir.resolve("shop.db"));store.create("general","일반 상점");product=store.add("general","커스텀 아이템",new byte[]{7,8},"10","5");}
 @AfterEach void close()throws Exception{store.close();}
 @Test void quantityRejectsZeroNegativeNonNumericAndOverflow(){for(String value:List.of("0","-1","x","2147483648","577","1.5",""))assertThrows(IllegalArgumentException.class,()->ShopProtocol.quantity(value));assertEquals(9,ShopProtocol.quantity("9"));}
 @Test void staleRevisionCannotPreparePayment()throws Exception{long rev=store.catalog().get("general").revision();store.prices("general",product,"20","5");assertThrows(Exception.class,()->store.prepare(owner,UUID.randomUUID().toString(),"general",rev,product,1,false));}
 @Test void heldOrderBlocksCrossConnectionAndNoDuplicateRequest()throws Exception{long rev=store.catalog().get("general").revision();String key=UUID.randomUUID().toString();var order=store.prepare(owner,key,"general",rev,product,2,false);try(var other=new ShopStore(DatabaseSettings.load(dir.resolve("missing.properties")),dir.resolve("shop.db"))){assertThrows(Exception.class,()->other.prepare(owner,UUID.randomUUID().toString(),"general",rev,product,2,false));}store.state(order.id(),"prepared","paid");assertEquals(1,store.paid(owner).size());assertEquals("20",order.total());store.state(order.id(),"paid","done");assertThrows(Exception.class,()->store.prepare(owner,key,"general",rev,product,2,false));}
 @Test void disabledBuyingAndSellingAreServerValidated()throws Exception{store.prices("general",product,"","");long rev=store.catalog().get("general").revision();assertThrows(Exception.class,()->store.prepare(owner,UUID.randomUUID().toString(),"general",rev,product,1,false));assertThrows(Exception.class,()->store.prepare(owner,UUID.randomUUID().toString(),"general",rev,product,1,true));}
 @Test void fullOriginalPayloadIsRetained()throws Exception{assertArrayEquals(new byte[]{7,8},store.catalog().get("general").products().getFirst().bytes());}
 @Test void catalogVersionAndServerScopedBindingUpdate()throws Exception{long v=store.version();store.bind("server-a","citizens:1","general");assertTrue(store.version()>v);assertEquals("general",store.bindings("server-a").get("citizens:1"));assertTrue(store.bindings("server-b").isEmpty());}
 @Test void invalidPriceAndTotalOverflowAreRejected()throws Exception{assertThrows(Exception.class,()->ShopStore.price("-1"));assertThrows(Exception.class,()->ShopStore.price("NaN"));store.prices("general",product,"1000000000000","5");long rev=store.catalog().get("general").revision();assertThrows(Exception.class,()->store.prepare(owner,UUID.randomUUID().toString(),"general",rev,product,2,false));}
 @Test void tradesLockButNeverBumpCatalogVersion()throws Exception{long rev=store.catalog().get("general").revision(),v=store.version();var order=store.prepare(owner,UUID.randomUUID().toString(),"general",rev,product,1,false,"server-a");store.state(order.id(),"prepared","paying");store.state(order.id(),"paying","paid");store.state(order.id(),"paid","done");assertEquals(v,store.version());assertEquals(rev,store.catalog().get("general").revision());store.prices("general",product,"11","5");assertTrue(store.version()>v);assertEquals(List.of("general"),store.shopIds());}
 @Test void orderStatesAreCompareAndSwap()throws Exception{long rev=store.catalog().get("general").revision();var order=store.prepare(owner,UUID.randomUUID().toString(),"general",rev,product,3,false,"server-a");var open=store.open(owner);assertEquals(1,open.size());assertEquals("server-a",open.getFirst().origin());assertEquals("prepared",open.getFirst().state());assertTrue(open.getFirst().created()>0);assertEquals("30",open.getFirst().total());
  // 자동 실패와 결제 진행이 겹치면 한쪽만 이긴다: 진 쪽은 부작용을 실행하지 않는다.
  assertTrue(store.move(order.id(),List.of("prepared"),"failed"));assertThrows(IllegalStateException.class,()->store.state(order.id(),"prepared","paying"));assertFalse(store.move(order.id(),List.of("prepared","paying"),"failed"));assertTrue(store.open(owner).isEmpty());assertEquals("failed",store.order(order.id()).state());assertNull(store.order(UUID.randomUUID().toString()));}
 @Test void adminResolutionIsIdempotentAndUnblocksTrading()throws Exception{long rev=store.catalog().get("general").revision();var order=store.prepare(owner,UUID.randomUUID().toString(),"general",rev,product,1,false,"server-a");store.state(order.id(),"prepared","paying");assertThrows(Exception.class,()->store.prepare(owner,UUID.randomUUID().toString(),"general",rev,product,1,false,"server-a"));
  assertEquals("paying",store.adminMove(order.id(),List.of("prepared","paying","refunding"),"refunding").state());assertEquals("refunding",store.adminMove(order.id(),List.of("prepared","paying","refunding"),"refunding").state());assertThrows(IllegalStateException.class,()->store.adminMove(order.id(),List.of("prepared","paying","paid"),"paid"));
  store.state(order.id(),"refunding","failed");assertThrows(IllegalStateException.class,()->store.adminMove(order.id(),List.of("prepared","paying","refunding"),"refunding"));assertThrows(IllegalArgumentException.class,()->store.adminMove(UUID.randomUUID().toString(),List.of("prepared"),"failed"));assertNotNull(store.prepare(owner,UUID.randomUUID().toString(),"general",rev,product,1,false,"server-a"));}
 @Test void startupClosesOnlyOwnUnpaidBuyOrders()throws Exception{long rev=store.catalog().get("general").revision();UUID b=UUID.randomUUID(),c=UUID.randomUUID(),d=UUID.randomUUID();var mine=store.prepare(owner,UUID.randomUUID().toString(),"general",rev,product,1,false,"server-a");var other=store.prepare(b,UUID.randomUUID().toString(),"general",rev,product,1,false,"server-b");var sale=store.prepare(c,UUID.randomUUID().toString(),"general",rev,product,1,true,"server-a");var legacy=store.prepare(d,UUID.randomUUID().toString(),"general",rev,product,1,false);
  assertEquals("",legacy.origin());assertEquals(0,store.failPrepared(""));assertEquals(1,store.failPrepared("server-a"));assertEquals("failed",store.order(mine.id()).state());for(var kept:List.of(other,sale,legacy))assertEquals("prepared",store.order(kept.id()).state());assertEquals("sell",store.open(c).getFirst().mode());}
 @Test void reopeningAddsOriginColumnOnce()throws Exception{try(var again=new ShopStore(DatabaseSettings.load(dir.resolve("missing.properties")),dir.resolve("shop.db"))){long rev=again.catalog().get("general").revision();assertEquals("server-z",again.prepare(owner,UUID.randomUUID().toString(),"general",rev,product,1,false,"server-z").origin());}}
}
