package school.magiccodex.paper;
import static org.junit.jupiter.api.Assertions.*;import java.util.*;import org.junit.jupiter.api.Test;import school.magiccodex.protocol.ShopAdminProtocol;import school.magiccodex.protocol.ShopAdminProtocol.*;
class ShopAdminProtocolTest {
 Request request(int action,String price){return new Request(action,1,42,"a",2,UUID.randomUUID().toString(),"상품",price,"off","검색",0);}
 @Test void mutationRoundTripAndDisabledPrice(){var r=request(ShopAdminProtocol.EDIT,"123.456789");assertEquals(r,ShopAdminProtocol.request(ShopAdminProtocol.encode(r)));assertDoesNotThrow(()->ShopAdminProtocol.price("off"));assertDoesNotThrow(()->ShopAdminProtocol.price("0"));}
 @Test void rejectsPricesAndNamesBeforeHandler(){for(String p:List.of("-1","NaN","1e3","1000000000001","0.1234567",""))assertThrows(IllegalArgumentException.class,()->ShopAdminProtocol.request(ShopAdminProtocol.encode(request(ShopAdminProtocol.ADD,p))));var r=request(ShopAdminProtocol.EDIT,"1");assertThrows(IllegalArgumentException.class,()->ShopAdminProtocol.request(ShopAdminProtocol.encode(new Request(r.action(),1,42,"a",2,r.product(),"","\u0031","off","",0))));}
 @Test void rejectsWrongSessionBadActionAndTrailingBytes(){var r=request(ShopAdminProtocol.LIST,"off");byte[] good=ShopAdminProtocol.encode(r);assertThrows(IllegalArgumentException.class,()->ShopAdminProtocol.request(Arrays.copyOf(good,good.length+1)));assertThrows(IllegalArgumentException.class,()->ShopAdminProtocol.request(ShopAdminProtocol.encode(new Request(99,1,42,"a",2,"","","off","off","",0))));assertThrows(IllegalArgumentException.class,()->ShopAdminProtocol.request(ShopAdminProtocol.encode(new Request(0,1,0,"a",2,"","","off","off","",0))));}
 @Test void fullPreviewAndPaginationRoundTrip(){byte[] b=new byte[32768];Arrays.fill(b,(byte)9);var response=new Response(1,42,"a",2,"",List.of(new Shop("a","상점")),List.of(new Product(UUID.randomUUID().toString(),"커스텀","0","",b)),5,6);var actual=ShopAdminProtocol.response(ShopAdminProtocol.encode(response));assertArrayEquals(b,actual.products().getFirst().preview());assertEquals(6,actual.nextOffset());assertEquals("상점",actual.shops().getFirst().title());}
 @Test void malformedPreviewAndOversizedPacketsRejected(){var response=new Response(1,42,"a",2,"",List.of(),List.of(new Product(UUID.randomUUID().toString(),"상품","0","",new byte[32769])),0,-1);assertThrows(IllegalArgumentException.class,()->ShopAdminProtocol.response(ShopAdminProtocol.encode(response)));assertThrows(IllegalArgumentException.class,()->ShopAdminProtocol.request(new byte[60001]));}
}
