package school.magiccodex.client;
import static org.junit.jupiter.api.Assertions.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import school.magiccodex.protocol.ShopProtocol;
class UiFollowupTest {
 @Test void queuedCommandCannotOpenInSameTick(){var q=new NextTickAction();Object c=new Object(),w=new Object();int[] count={0};q.schedule(c,w,()->count[0]++);q.drain(c,w);assertEquals(0,count[0]);q.advance();q.drain(c,w);q.drain(c,w);assertEquals(1,count[0]);}
 @Test void cancelledOrTransferredConnectionCannotOpenStaleScreen(){var q=new NextTickAction();Object c=new Object(),w=new Object();int[] count={0};q.schedule(c,w,()->count[0]++);q.advance();q.drain(new Object(),w);q.drain(c,w);assertEquals(0,count[0]);q.schedule(c,w,()->count[0]++);q.cancel();q.advance();q.drain(c,w);assertEquals(0,count[0]);q.schedule(c,w,()->count[0]++);q.advance();q.drain(c,new Object());assertEquals(0,count[0]);}
 @Test void latestOpenWinsAndDisconnectedWorldCancels(){var q=new NextTickAction();Object c=new Object(),w=new Object();int[] count={0};q.schedule(c,w,()->count[0]+=1);q.schedule(c,w,()->count[0]+=10);q.advance();q.drain(c,w);assertEquals(10,count[0]);q.schedule(c,w,()->count[0]++);q.advance();q.drain(null,null);q.drain(c,w);assertEquals(10,count[0]);}
 @Test void dialogueRejectsDuplicateUnknownAndLateReplies(){var f=new NpcTalkFlow();assertEquals(1,f.begin(100));assertEquals(0,f.begin(101));assertFalse(f.line(2));assertTrue(f.waiting());assertTrue(f.line(1));assertFalse(f.waiting());assertFalse(f.line(1));assertEquals(2,f.begin(200));assertFalse(f.line(1));assertTrue(f.line(2));}
 @Test void failedSendAndServerInfoReleasePendingButNotSequenceFence(){var f=new NpcTalkFlow();f.begin(10);f.rejected(9);assertTrue(f.waiting());f.rejected(1);assertFalse(f.waiting());assertEquals(2,f.begin(20));assertFalse(f.line(1));assertTrue(f.matches(2));}
 @Test void timeoutAllowsLateReplyUntilANewerRequest(){var f=new NpcTalkFlow();f.begin(10);assertFalse(f.timeout(20010));assertTrue(f.timeout(20011));assertTrue(f.line(1));f.begin(30000);assertTrue(f.timeout(50001));f.begin(50002);assertFalse(f.line(2));assertTrue(f.line(3));}
 @Test void historyKeepsPlayerChoicesAndDirectTextWithoutDuplicateReplies(){var h=new ConversationHistory();h.add("player:1","나","선택한 말");h.add("npc:1","엘라","대답");h.add("npc:1","엘라","대답");h.add("player:2","나","직접 말한 문장");h.add("npc:2","엘라","대답");assertEquals(4,h.entries().size());assertEquals("직접 말한 문장",h.entries().get(2).text());}
 @Test void historyRetainsMostRecentEightyEntries(){var h=new ConversationHistory();for(int i=0;i<100;i++)h.add("npc:"+i,"NPC","말 "+i);assertEquals(80,h.entries().size());assertEquals("말 20",h.entries().getFirst().text());assertEquals("말 99",h.entries().getLast().text());}
 private ShopProtocol.Response reply(long sequence,long session,String receipt){return new ShopProtocol.Response(sequence,session,"general","상점","elena-neutral",1,"100","완료",List.of(),receipt);}
 @Test void tradeSoundRequiresMatchingSuccessfulReceiptAndIsOnceOnly(){var f=new ShopFeedback();String op=UUID.randomUUID().toString();var success=reply(9,77,op);assertFalse(f.success(reply(9,77,""),9,77,"general",ShopProtocol.BUY,op));assertFalse(f.success(success,9,77,"general",ShopProtocol.OPEN,op));assertFalse(f.success(success,9,88,"general",ShopProtocol.BUY,op));assertFalse(f.success(success,10,77,"general",ShopProtocol.BUY,op));assertFalse(f.success(success,9,77,"other",ShopProtocol.BUY,op));assertTrue(f.success(success,9,77,"general",ShopProtocol.BUY,op));assertFalse(f.success(success,9,77,"general",ShopProtocol.BUY,op));assertTrue(f.success(reply(10,77,"second"),10,77,"general",ShopProtocol.SELL,"second"));}
}