package school.magiccodex.protocol;
import java.io.*;import java.util.*;
/** Operator channel: item bytes only travel from the server. */
public final class ShopAdminProtocol {
 public static final String REQUEST="magiccodex:shop_admin_request",RESPONSE="magiccodex:shop_admin_response";
 public static final int MAX_BYTES=60000,MAX_PREVIEW=32768,LIST=0,ADD=1,EDIT=2,DELETE=3,CLOSE=4;
 public record Request(int action,long sequence,long session,String shop,long revision,String product,String name,String buy,String sell,String search,int offset){}
 public record Shop(String id,String title){}
 public record Product(String id,String name,String buy,String sell,byte[] preview){}
 public record Response(long sequence,long session,String shop,long revision,String message,List<Shop> shops,List<Product> products,int offset,int nextOffset){}
 private interface Write{void run(DataOutputStream out)throws IOException;}
 private static byte[] pack(Write w){try{var b=new ByteArrayOutputStream();var o=new DataOutputStream(b);o.writeInt(0x53414431);w.run(o);if(b.size()>MAX_BYTES)throw new IOException("size");return b.toByteArray();}catch(IOException e){throw new IllegalArgumentException(e);}}
 private static DataInputStream input(byte[] b)throws IOException{if(b.length<4||b.length>MAX_BYTES)throw new IOException("size");var i=new DataInputStream(new ByteArrayInputStream(b));if(i.readInt()!=0x53414431)throw new IOException("version");return i;}
 private static String text(DataInputStream i,int max)throws IOException{String s=i.readUTF();if(s.length()>max)throw new IOException("text");return s;}
 public static byte[] encode(Request r){return pack(o->{o.writeByte(r.action);o.writeLong(r.sequence);o.writeLong(r.session);o.writeUTF(r.shop);o.writeLong(r.revision);o.writeUTF(r.product);o.writeUTF(r.name);o.writeUTF(r.buy);o.writeUTF(r.sell);o.writeUTF(r.search);o.writeInt(r.offset);});}
 public static Request request(byte[] bytes){try{var i=input(bytes);var r=new Request(i.readUnsignedByte(),i.readLong(),i.readLong(),text(i,48),i.readLong(),text(i,36),text(i,120),text(i,32),text(i,32),text(i,80),i.readInt());if(i.available()!=0||r.action<0||r.action>CLOSE||r.sequence<=0||r.session<=0||r.offset<0||r.offset>1000000||!r.shop.matches("[a-z0-9_-]{0,48}"))throw new IOException("request");if(r.action==EDIT||r.action==DELETE)UUID.fromString(r.product);if(r.action==ADD||r.action==EDIT){if(r.shop.isEmpty()||r.revision<1)throw new IOException("shop");price(r.buy);price(r.sell);if(r.name.isBlank()||r.name.codePoints().anyMatch(Character::isISOControl))throw new IOException("name");}return r;}catch(IOException|RuntimeException e){throw new IllegalArgumentException("shop admin request",e);}}
 public static void price(String s){if(s.equals("off"))return;if(!s.matches("[0-9]{1,13}(\\.[0-9]{1,6})?"))throw new IllegalArgumentException("가격 형식");if(new java.math.BigDecimal(s).compareTo(new java.math.BigDecimal("1000000000000"))>0)throw new IllegalArgumentException("가격 한도");}
 public static byte[] encode(Response r){return pack(o->{o.writeLong(r.sequence);o.writeLong(r.session);o.writeUTF(r.shop);o.writeLong(r.revision);o.writeUTF(r.message);o.writeInt(r.shops.size());for(var s:r.shops){o.writeUTF(s.id);o.writeUTF(s.title);}o.writeInt(r.products.size());for(var p:r.products){o.writeUTF(p.id);o.writeUTF(p.name);o.writeUTF(p.buy);o.writeUTF(p.sell);o.writeInt(p.preview.length);o.write(p.preview);}o.writeInt(r.offset);o.writeInt(r.nextOffset);});}
 public static Response response(byte[] bytes){try{var i=input(bytes);long seq=i.readLong(),token=i.readLong();String shop=text(i,48);long rev=i.readLong();String message=text(i,240);int n=i.readInt();if(n<0||n>128)throw new IOException("shops");var shops=new ArrayList<Shop>();for(int x=0;x<n;x++)shops.add(new Shop(text(i,48),text(i,80)));n=i.readInt();if(n<0||n>20)throw new IOException("products");var ps=new ArrayList<Product>();for(int x=0;x<n;x++){String id=text(i,36),name=text(i,120),buy=text(i,32),sell=text(i,32);int size=i.readInt();if(size<0||size>MAX_PREVIEW)throw new IOException("preview");byte[] b=i.readNBytes(size);if(b.length!=size)throw new IOException("preview");ps.add(new Product(id,name,buy,sell,b));}int offset=i.readInt(),next=i.readInt();if(i.available()!=0||token<=0||seq<0||offset<0||next < -1)throw new IOException("response");return new Response(seq,token,shop,rev,message,List.copyOf(shops),List.copyOf(ps),offset,next);}catch(IOException|RuntimeException e){throw new IllegalArgumentException("shop admin response",e);}}
}
