package school.magiccodex.protocol;
import java.io.*;import java.util.*;
public final class ShopProtocol {
 public static final String REQUEST="magiccodex:shop_request",RESPONSE="magiccodex:shop_response";public static final int MAX_BYTES=60000,MAX_PREVIEW_BYTES=32768,OPEN=0,BUY=1,SELL=2,CLOSE=3;
 public record Request(int action,long sequence,long session,String shop,long revision,String product,String quantity,String operation,String search){}
 public record Product(String id,String name,String buy,String sell,int owned,byte[] preview){}
 public record Response(long sequence,long session,String shop,String title,String portrait,long revision,String balance,String message,List<Product> products,String completedOperation){
 public Response(long sequence,long session,String shop,String title,String portrait,long revision,String balance,String message,List<Product> products){this(sequence,session,shop,title,portrait,revision,balance,message,products,"");}
 }
 private interface Write{void run(DataOutputStream o)throws IOException;}
 private static byte[] pack(Write f){try{var b=new ByteArrayOutputStream();var o=new DataOutputStream(b);o.writeInt(0x53485032);f.run(o);if(b.size()>MAX_BYTES)throw new IOException("size");return b.toByteArray();}catch(IOException e){throw new IllegalArgumentException(e);}}
 public static byte[] encode(Request r){return pack(o->{o.writeByte(r.action);o.writeLong(r.sequence);o.writeLong(r.session);o.writeUTF(r.shop);o.writeLong(r.revision);o.writeUTF(r.product);o.writeUTF(r.quantity);o.writeUTF(r.operation);o.writeUTF(r.search);});}
 public static byte[] encode(Response r){return pack(o->{o.writeLong(r.sequence);o.writeLong(r.session);o.writeUTF(r.shop);o.writeUTF(r.title);o.writeUTF(r.portrait);o.writeLong(r.revision);o.writeUTF(r.balance);o.writeUTF(r.message);o.writeInt(r.products.size());for(var p:r.products){o.writeUTF(p.id);o.writeUTF(p.name);o.writeUTF(p.buy);o.writeUTF(p.sell);o.writeInt(p.owned);o.writeInt(p.preview.length);o.write(p.preview);}o.writeUTF(r.completedOperation);});}
 private static DataInputStream input(byte[] b)throws IOException{if(b.length<4||b.length>MAX_BYTES)throw new IOException("size");var i=new DataInputStream(new ByteArrayInputStream(b));if(i.readInt()!=0x53485032)throw new IOException("version");return i;}
 private static String text(DataInputStream i,int max)throws IOException{var s=i.readUTF();if(s.length()>max)throw new IOException("text");return s;}
 public static Request request(byte[] b){try{var i=input(b);var r=new Request(i.readUnsignedByte(),i.readLong(),i.readLong(),text(i,48),i.readLong(),text(i,36),text(i,10),text(i,36),text(i,80));if(i.available()!=0||r.action<0||r.action>CLOSE||r.sequence<=0||!r.shop.matches("[a-z0-9_-]{1,48}"))throw new IOException("request");if(r.action==BUY||r.action==SELL){UUID.fromString(r.product);UUID.fromString(r.operation);quantity(r.quantity);}return r;}catch(IOException|RuntimeException e){throw new IllegalArgumentException("shop request",e);}}
 public static int quantity(String value){if(value==null||!value.matches("[0-9]{1,9}"))throw new IllegalArgumentException("quantity");int n=Integer.parseInt(value);if(n<1||n>576)throw new IllegalArgumentException("quantity limit");return n;}
 public static Response response(byte[] b){try{var i=input(b);long sequence=i.readLong(),session=i.readLong();String shop=text(i,48),title=text(i,80),portrait=text(i,120);long revision=i.readLong();String balance=text(i,40),message=text(i,240);int n=i.readInt();if(n<0||n>40)throw new IOException("products");var ps=new ArrayList<Product>();for(int x=0;x<n;x++){String id=text(i,36),name=text(i,120),buy=text(i,32),sell=text(i,32);int owned=i.readInt(),size=i.readInt();if(owned<0||size<0||size>MAX_PREVIEW_BYTES)throw new IOException("product");byte[] preview=i.readNBytes(size);if(preview.length!=size)throw new IOException("preview");ps.add(new Product(id,name,buy,sell,owned,preview));}String completed=text(i,36);if(!completed.isEmpty())UUID.fromString(completed);if(i.available()!=0)throw new IOException("trailing");return new Response(sequence,session,shop,title,portrait,revision,balance,message,List.copyOf(ps),completed);}catch(IOException|RuntimeException e){throw new IllegalArgumentException("shop response",e);}}
}
