plugins {
    id 'java'
}

group = 'kr.chacademy'
version = '0.1.0'

repositories {
    mavenCentral()
    maven { name = 'papermc'; url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

processResources {
    inputs.property 'version', project.version
    filesMatching('plugin.yml') {
        expand 'version': project.version
    }
}
