package school.magiccodex.paper;
import java.math.BigDecimal;import java.nio.file.*;import java.util.*;import java.util.concurrent.*;import java.util.function.*;
import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.player.*;import org.bukkit.inventory.ItemStack;import org.bukkit.persistence.PersistentDataType;import org.bukkit.plugin.messaging.PluginMessageListener;
import school.magiccodex.protocol.ShopProtocol;import school.magiccodex.protocol.ShopProtocol.*;

/** Admin shops only. Money and inventory effects are journalled, never retried blindly after ambiguity. */
final class ShopBridge implements PluginMessageListener,Listener,CommandExecutor,TabCompleter,AutoCloseable {
 private final MagicCodexBridge plugin;private final ShopStore store;private final String origin;
 private final ThreadPoolExecutor io=new ThreadPoolExecutor(1,1,0,TimeUnit.MILLISECONDS,new ArrayBlockingQueue<>(64),r->{var t=new Thread(r,"MagicCodex-shop-io");t.setDaemon(true);return t;});
 private Map<String,ShopStore.Shop> catalog=Map.of();private Map<String,String> bindings=Map.of();private long version=-1;private boolean refreshing,closing;
 private record Session(Player player,long token,long sequence,String shop,Entity anchor){}
 private final Map<UUID,Session> sessions=new HashMap<>();private final Set<UUID>busy=new HashSet<>();private final Map<UUID,Long>limits=new HashMap<>();
 ShopBridge(MagicCodexBridge plugin)throws Exception{this.plugin=plugin;var dir=plugin.getDataFolder().toPath();origin=Files.readString(dir.resolve("mailbox-origin.txt")).strip();try{store=io.submit(()->new ShopStore(ShopMailboxDatabaseSettings.load(dir),dir.resolve("shops.db"))).get(15,TimeUnit.SECONDS);}catch(Exception e){io.shutdownNow();throw e;}
  catalog=io.submit(store::catalog).get(10,TimeUnit.SECONDS);bindings=io.submit(()->store.bindings(origin)).get(10,TimeUnit.SECONDS);version=io.submit(store::version).get(10,TimeUnit.SECONDS);
  Bukkit.getMessenger().registerIncomingPluginChannel(plugin,ShopProtocol.REQUEST,this);Bukkit.getMessenger().registerOutgoingPluginChannel(plugin,ShopProtocol.RESPONSE);Bukkit.getPluginManager().registerEvents(this,plugin);Bukkit.getServicesManager().register(ShopBridge.class,this,plugin,org.bukkit.plugin.ServicePriority.Normal);plugin.getCommand("상점").setExecutor(this);plugin.getCommand("상점관리").setExecutor(this);plugin.getCommand("상점").setTabCompleter(this);plugin.getCommand("상점관리").setTabCompleter(this);citizens();refreshCompletionKeys();Bukkit.getScheduler().runTaskTimer(plugin,this::refresh,100,100);
 }
 private void main(Runnable r){if(!closing&&plugin.isEnabled())Bukkit.getScheduler().runTask(plugin,r);}
 private <T>void work(Callable<T>task,Consumer<T>success,Consumer<String>fail){try{io.execute(()->{try{T v=task.call();main(()->success.accept(v));}catch(Exception e){plugin.getLogger().warning("Shop operation held: "+e.getClass().getSimpleName());main(()->fail.accept(e instanceof IllegalArgumentException||e instanceof IllegalStateException?e.getMessage():"거래 기록 확인이 필요합니다. 자동으로 재처리하지 않습니다."));}});}catch(RejectedExecutionException e){fail.accept("상점이 바쁩니다. 잠시 뒤 다시 시도해 주세요.");}}
 private record Catalog(long version,Map<String,ShopStore.Shop> shops,Map<String,String> bindings){}
 private void refresh(){if(refreshing||closing)return;refreshing=true;work(()->{long v=store.version();return v==version?null:new Catalog(v,store.catalog(),store.bindings(origin));},c->{refreshing=false;if(c!=null){version=c.version;catalog=c.shops;bindings=c.bindings;}refreshCompletionKeys();},m->refreshing=false);}
 private boolean current(Player p){return !closing&&p.isOnline()&&Bukkit.getPlayer(p.getUniqueId())==p;}
 private boolean ready(Player p){return current(p)&&p.hasPermission("magiccodex.shop")&&!p.isDead()&&p.getGameMode()!=GameMode.SPECTATOR&&plugin.playerStateReady(p);}
 private boolean near(Player p,Entity anchor){return anchor==null||anchor.isValid()&&p.getWorld()==anchor.getWorld()&&p.getLocation().distanceSquared(anchor.getLocation())<=64;}
 private record Economy(Class<?>type,Object provider){}
 @SuppressWarnings({"rawtypes","unchecked"})private Economy economy(){for(Class<?>type:Bukkit.getServicesManager().getKnownServices())if(type.getName().equals("net.milkbowl.vault.economy.Economy")){var r=Bukkit.getServicesManager().getRegistration((Class)type);if(r!=null)return new Economy(type,r.getProvider());}return null;}
 private double balance(Player p)throws Exception{var e=economy();if(e==null)throw new IllegalStateException("경제 서비스 연결이 필요합니다.");double v=((Number)e.type.getMethod("getBalance",OfflinePlayer.class).invoke(e.provider,p)).doubleValue();if(!Double.isFinite(v)||v<0)throw new IllegalStateException("잔액을 확인할 수 없습니다.");return v;}
 private boolean money(Player p,String amount,boolean deposit)throws Exception{var e=economy();if(e==null)throw new IllegalStateException("경제 서비스 연결이 필요합니다.");var cost=new BigDecimal(amount);int digits=((Number)e.type.getMethod("fractionalDigits").invoke(e.provider)).intValue();if(digits>=0&&cost.stripTrailingZeros().scale()>digits)throw new IllegalStateException("경제 서비스가 지원하는 소수점 자릿수를 확인하세요.");if(!deposit&&BigDecimal.valueOf(balance(p)).compareTo(cost)<0)return false;if(cost.signum()==0)return true;Object result=e.type.getMethod(deposit?"depositPlayer":"withdrawPlayer",OfflinePlayer.class,double.class).invoke(e.provider,p,cost.doubleValue());return (boolean)result.getClass().getMethod("transactionSuccess").invoke(result);}
 private int owned(Player p,ItemStack sample){int n=0;for(var i:p.getInventory().getStorageContents())if(i!=null&&i.isSimilar(sample))n+=i.getAmount();return n;}
 private void open(Player p,String id,Entity anchor){if(!ready(p)||!near(p,anchor)||busy.contains(p.getUniqueId())||!catalog.containsKey(id))return;var s=new Session(p,ThreadLocalRandom.current().nextLong(1,Long.MAX_VALUE),0,id,anchor);sessions.put(p.getUniqueId(),s);send(p,s,0,"","");busy.add(p.getUniqueId());work(()->store.paid(p.getUniqueId()),paid->{if(paid.isEmpty()){busy.remove(p.getUniqueId());return;}var r=new Request(ShopProtocol.OPEN,0,s.token,id,0,"","1","","");deliver(p,s,r,paid.getFirst());},m->{busy.remove(p.getUniqueId());if(current(p))send(p,s,0,m,"");});}
 String openBound(Player p,int npcId,Entity anchor){String id=bindings.get("citizens:"+npcId);if(id==null)return "NONE";if(!ready(p)||!near(p,anchor)||!catalog.containsKey(id))return "BLOCKED";if(busy.contains(p.getUniqueId()))return "BUSY";if(!p.getListeningPluginChannels().contains(ShopProtocol.RESPONSE)){p.sendMessage("상점 모드를 업데이트해 주세요.");return "BLOCKED";}open(p,id,anchor);return "OPENED";}
 private void send(Player p,Session s,long sequence,String message,String search){send(p,s,sequence,message,search,"");}
 private void send(Player p,Session s,long sequence,String message,String search,String completedOperation){
  if(!current(p))return;var shop=catalog.get(s.shop);if(shop==null)return;
  String cash="";try{cash=BigDecimal.valueOf(balance(p)).stripTrailingZeros().toPlainString();}catch(Exception ignored){}
  var list=new ArrayList<Product>();String q=search.toLowerCase(Locale.ROOT);int bytes=0;boolean limited=false;
  for(var item:shop.products())if(item.name().toLowerCase(Locale.ROOT).contains(q)){
   // Keep the complete original serialized stack. Limit the catalogue page, never strip lore/components.
   byte[] preview=item.bytes();int cost=preview.length+1000;
   if(preview.length>ShopProtocol.MAX_PREVIEW_BYTES||bytes+cost>ShopProtocol.MAX_BYTES-4096||list.size()==40){limited=true;break;}
   var stack=ItemStack.deserializeBytes(preview);list.add(new Product(item.id(),item.name(),item.buy(),item.sell(),owned(p,stack),preview));bytes+=cost;
  }
  if(limited&&message.isEmpty())message="검색으로 상품을 좁혀 주세요. 전체 아이템 정보를 유지해 목록을 제한합니다.";
  p.sendPluginMessage(plugin,ShopProtocol.RESPONSE,ShopProtocol.encode(new Response(sequence,s.token,shop.id(),shop.title(),shop.portrait(),shop.revision(),cash,message,List.copyOf(list),completedOperation,npcName(s.anchor))));
 }
 private String npcName(Entity anchor){
  if(anchor==null)return "";
  try{var dep=Bukkit.getPluginManager().getPlugin("Citizens");if(dep!=null){Class<?> api=Class.forName("net.citizensnpcs.api.CitizensAPI",true,dep.getClass().getClassLoader());Object registry=api.getMethod("getNPCRegistry").invoke(null);Class<?> registryType=Class.forName("net.citizensnpcs.api.npc.NPCRegistry",true,dep.getClass().getClassLoader());Object npc=registryType.getMethod("getNPC",Entity.class).invoke(registry,anchor);if(npc!=null){Class<?> npcType=Class.forName("net.citizensnpcs.api.npc.NPC",true,dep.getClass().getClassLoader());String value=String.valueOf(npcType.getMethod("getName").invoke(npc));return value.length()>120?value.substring(0,120):value;}}}catch(ReflectiveOperationException ignored){}
  var custom=anchor.customName();if(custom==null)return "";String value=net.kyori.adventure.text.serializer.plain.PlainTextComponentSerializer.plainText().serialize(custom);return value.length()>120?value.substring(0,120):value;
 }
 @Override public void onPluginMessageReceived(String channel,Player p,byte[] bytes){if(!channel.equals(ShopProtocol.REQUEST)||!ready(p))return;Request r;try{r=ShopProtocol.request(bytes);}catch(IllegalArgumentException ignored){return;}var s=sessions.get(p.getUniqueId());if(s==null||s.player!=p||s.token!=r.session()||!s.shop.equals(r.shop())||r.sequence()<=s.sequence||!near(p,s.anchor))return;long now=System.currentTimeMillis();if(busy.contains(p.getUniqueId())||now<limits.getOrDefault(p.getUniqueId(),0L))return;limits.put(p.getUniqueId(),now+200);s=new Session(p,s.token,r.sequence(),s.shop,s.anchor);sessions.put(p.getUniqueId(),s);if(r.action()==ShopProtocol.CLOSE){sessions.remove(p.getUniqueId());return;}if(r.action()==ShopProtocol.OPEN){send(p,s,r.sequence(),"",r.search());return;}trade(p,s,r);}
 private void trade(Player p,Session s,Request r){var shop=catalog.get(s.shop);var product=shop==null?null:shop.products().stream().filter(i->i.id().equals(r.product())).findFirst().orElse(null);if(product==null||shop.revision()!=r.revision()){send(p,s,r.sequence(),"상점 설정이 변경되었습니다. 다시 확인해 주세요.",r.search());return;}int quantity=ShopProtocol.quantity(r.quantity());boolean selling=r.action()==ShopProtocol.SELL;var sample=ItemStack.deserializeBytes(product.bytes());if(quantity>sample.getMaxStackSize()*9){send(p,s,r.sequence(),"한 거래의 우편 첨부 가능 수량을 초과했습니다.",r.search());return;}if(economy()==null){send(p,s,r.sequence(),"경제 서비스 연결이 필요합니다.",r.search());return;}var before=MailboxBridge.copy(p.getInventory().getStorageContents());var after=MailboxBridge.copy(before);if(selling){if(owned(p,sample)<quantity){send(p,s,r.sequence(),"판매할 아이템 수량이 부족합니다.",r.search());return;}int left=quantity;for(int i=0;i<after.length&&left>0;i++)if(after[i]!=null&&after[i].isSimilar(sample)){int n=Math.min(left,after[i].getAmount());left-=n;after[i].setAmount(after[i].getAmount()-n);if(after[i].getAmount()==0)after[i]=null;}}
  UUID owner=p.getUniqueId();busy.add(owner);work(()->store.prepare(owner,r.operation(),s.shop,r.revision(),r.product(),quantity,selling),order->{
   if(!ready(p)||!near(p,s.anchor)||selling&&!MailboxBridge.same(before,p.getInventory().getStorageContents())){state(order,"prepared","failed",()->done(p,s,r,"접속/인벤토리가 변경되었습니다."));return;}
   if(selling){try{p.getInventory().setStorageContents(after);p.getPersistentDataContainer().set(new NamespacedKey(plugin,"shop_sale_"+order.id().replace("-","")),PersistentDataType.BYTE,(byte)1);p.saveData();}catch(RuntimeException e){done(p,s,r,"판매 저장을 확인해야 합니다. 자동으로 재처리하지 않습니다.");return;}saleSaved(order,p,()->state(order,"sale_removed","credit_pending",()->{try{if(!money(p,order.total(),true)){done(p,s,r,"돈 지급이 완료되지 않았습니다. 거래 기록 확인이 필요합니다.");return;}state(order,"credit_pending","done",()->{if(current(p)){p.getPersistentDataContainer().remove(new NamespacedKey(plugin,"shop_sale_"+order.id().replace("-","")));p.saveData();}done(p,s,r,"판매가 완료되었습니다.",true);});}catch(Exception e){done(p,s,r,"돈 지급 결과 확인이 필요합니다. 자동으로 다시 지급하지 않습니다.");}}));}
   else{try{if(!money(p,order.total(),false)){state(order,"prepared","failed",()->done(p,s,r,"잔액이 부족하거나 결제가 거절되었습니다."));return;}state(order,"prepared","paid",()->deliver(p,s,r,order));}catch(Exception e){done(p,s,r,"결제 결과 확인이 필요합니다. 자동으로 다시 결제하지 않습니다.");}}
  },message->done(p,s,r,message));
 }
 private void state(ShopStore.Order order,String expected,String next,Runnable done){work(()->{store.state(order.id(),expected,next);return true;},v->done.run(),m->{busy.remove(order.owner());var p=Bukkit.getPlayer(order.owner());if(p!=null)p.sendMessage(m);});}
 private void saleSaved(ShopStore.Order order,Player p,Runnable done){var file=MailboxBridge.playerFile(p);String key=new NamespacedKey(plugin,"shop_sale_"+order.id().replace("-","")).toString();work(()->{if(!DeliveryReceipt.saved(file,key))throw new IllegalStateException("판매 아이템 저장 영수증 확인이 필요합니다.");store.state(order.id(),"prepared","sale_removed");return true;},v->done.run(),m->{busy.remove(order.owner());if(current(p))p.sendMessage(m);});}
 private void deliver(Player p,Session s,Request r,ShopStore.Order order){MailService mail=Bukkit.getServicesManager().load(MailService.class);if(mail==null){done(p,s,r,"결제 완료. 우편 저장 확인이 필요합니다.");return;}var sample=ItemStack.deserializeBytes(order.bytes());var attachments=new ArrayList<ItemStack>();int left=order.quantity();while(left>0){var stack=sample.clone();stack.setAmount(Math.min(left,sample.getMaxStackSize()));left-=stack.getAmount();attachments.add(stack);}mail.sendSystem("shop:"+order.id(),order.owner(),order.title().substring(0,Math.min(76,order.title().length()))+" 구매",order.quantity()+"개 상품을 구매했습니다.",attachments).whenComplete((id,error)->main(()->{if(error!=null){done(p,s,r,"결제 완료. 우편 저장 확인이 필요합니다. 다시 결제하지 마세요.");return;}state(order,"paid","done",()->done(p,s,r,"구매가 완료되었습니다.",true));}));}
 private void done(Player p,Session s,Request r,String message){done(p,s,r,message,false);}private void done(Player p,Session s,Request r,String message,boolean success){busy.remove(p.getUniqueId());var latest=sessions.get(p.getUniqueId());if(current(p)&&latest!=null&&latest.token==s.token&&latest.sequence==r.sequence())send(p,latest,r.sequence(),message,r.search(),success?r.operation():"");}
 @SuppressWarnings("unchecked")private void citizens(){var dep=Bukkit.getPluginManager().getPlugin("Citizens");if(dep==null)return;try{Class<? extends Event>type=(Class<? extends Event>)Class.forName("net.citizensnpcs.api.event.NPCRightClickEvent",true,dep.getClass().getClassLoader());Bukkit.getPluginManager().registerEvent(type,this,EventPriority.HIGH,(l,event)->{try{var npc=event.getClass().getMethod("getNPC").invoke(event);int npcId=((Number)npc.getClass().getMethod("getId").invoke(npc)).intValue();if(plugin.dialogueBridge()!=null&&plugin.dialogueBridge().claimed(npcId))return;String id="citizens:"+npcId;String shop=bindings.get(id);if(shop!=null){var p=(Player)event.getClass().getMethod("getClicker").invoke(event);var anchor=(Entity)npc.getClass().getMethod("getEntity").invoke(npc);if(event instanceof Cancellable c)c.setCancelled(true);open(p,shop,anchor);}}catch(Exception e){plugin.getLogger().warning("Shop NPC event unavailable");}},plugin,true);}catch(Exception e){plugin.getLogger().warning("Shop Citizens hook unavailable");}}
 @EventHandler(priority=EventPriority.HIGH,ignoreCancelled=true)public void interact(PlayerInteractEntityEvent e){if(e.getHand()!=org.bukkit.inventory.EquipmentSlot.HAND||e.getRightClicked().hasMetadata("NPC"))return;for(String tag:e.getRightClicked().getScoreboardTags()){String shop=bindings.get("tag:"+tag);if(shop!=null){e.setCancelled(true);open(e.getPlayer(),shop,e.getRightClicked());break;}}}

 private List<String> completionNpcKeys=List.of();
 private void refreshCompletionKeys(){
  var keys=new TreeSet<String>(bindings.keySet());
  var dep=Bukkit.getPluginManager().getPlugin("Citizens");
  if(dep!=null&&dep.isEnabled())try{
   ClassLoader loader=dep.getClass().getClassLoader();
   Object registry=Class.forName("net.citizensnpcs.api.CitizensAPI",true,loader).getMethod("getNPCRegistry").invoke(null);
   var idMethod=Class.forName("net.citizensnpcs.api.npc.NPC",true,loader).getMethod("getId");
   if(registry instanceof Iterable<?> npcs)for(Object npc:npcs){
    if(keys.size()>=4096)break;
    int id=((Number)idMethod.invoke(npc)).intValue();
    if(id>=0&&id<=999999999)keys.add("citizens:"+id);
   }
  }catch(Exception|LinkageError ignored){}
  completionNpcKeys=List.copyOf(keys);
 }
 @Override public List<String> onTabComplete(CommandSender sender,Command command,String alias,String[] args){
  if(closing)return List.of();
  boolean admin=sender.hasPermission("magiccodex.shop.admin");
  var onlineIds=admin&&args!=null&&args.length==2&&"기록".equals(args[0])
    ? Bukkit.getOnlinePlayers().stream().map(p->p.getUniqueId().toString()).toList():List.<String>of();
  return ShopCommandCompletion.complete(command.getName(),args,sender instanceof Player,
    sender.hasPermission("magiccodex.shop"),admin,catalog,completionNpcKeys,onlineIds);
 }

 @Override public boolean onCommand(CommandSender sender,Command command,String label,String[] args){if(command.getName().equals("상점")){if(sender instanceof Player p&&args.length==1)open(p,args[0],null);else sender.sendMessage("/상점 <상점ID>");return true;}if(!sender.hasPermission("magiccodex.shop.admin"))return true;try{if(args.length==0){sender.sendMessage("/상점관리 생성 <ID> <이름> | 아이템추가 <상점> <구매가/off> <매입가/off> | 가격 <상점> <상품UUID> <구매가/off> <매입가/off> | NPC <상점> <citizens:ID/tag:태그> | 초상 <상점> <초상ID> | 목록");return true;}Callable<String> task;
  switch(args[0]){case "기록"->{if(args.length!=2)throw new IllegalArgumentException("기록 플레이어UUID");UUID id=UUID.fromString(args[1]);task=()->String.join("\n",store.audit(id));}case "목록"->{if(args.length==2){var shop=catalog.get(args[1]);if(shop==null)throw new IllegalArgumentException("상점 없음");for(var product:shop.products())sender.sendMessage(product.id()+" "+product.name()+" 구매="+(product.buy().isEmpty()?"off":product.buy())+" 매입="+(product.sell().isEmpty()?"off":product.sell()));}else sender.sendMessage(String.join(", ",catalog.keySet()));return true;}case "생성"->{if(args.length!=3)throw new IllegalArgumentException("생성 ID 이름");task=()->{store.create(args[1],args[2]);return "상점을 생성했습니다.";};}case "아이템추가"->{if(!(sender instanceof Player p)||args.length!=4)throw new IllegalArgumentException("손에 아이템을 들고 아이템추가 상점 구매가/off 매입가/off");var item=p.getInventory().getItemInMainHand().clone();if(item.getType().isAir())throw new IllegalArgumentException("손에 아이템을 들어 주세요.");item.setAmount(1);byte[] bytes=item.serializeAsBytes();if(bytes.length>32768)throw new IllegalArgumentException("아이템 데이터가 너무 큽니다.");String name=net.kyori.adventure.text.serializer.plain.PlainTextComponentSerializer.plainText().serialize(item.displayName());if(name.length()>120)name=name.substring(0,120);String finalName=name,buy=ShopStore.price(args[2]),sell=ShopStore.price(args[3]);task=()->"상품 ID: "+store.add(args[1],finalName,bytes,buy,sell);}case "가격"->{if(args.length!=5)throw new IllegalArgumentException("가격 상점 상품UUID 구매가/off 매입가/off");String buy=ShopStore.price(args[3]),sell=ShopStore.price(args[4]);task=()->{store.prices(args[1],args[2],buy,sell);return "가격/구매·매입 허용을 변경했습니다.";};}case "NPC"->{if(args.length!=3)throw new IllegalArgumentException("NPC 상점 citizens:ID/tag:태그");task=()->{store.bind(origin,args[2],args[1]);return "이 서버 NPC와 상점을 연결했습니다.";};}case "초상"->{if(args.length!=3)throw new IllegalArgumentException("초상 상점 초상ID");task=()->{store.portrait(args[1],args[2]);return "초상을 변경했습니다.";};}default->throw new IllegalArgumentException("지원하지 않는 관리 명령");}work(task,m->{sender.sendMessage(m);refresh();},sender::sendMessage);
 }catch(Exception e){sender.sendMessage(e.getMessage()==null?"설정을 확인하세요.":e.getMessage());}return true;}
 @EventHandler public void quit(PlayerQuitEvent e){sessions.remove(e.getPlayer().getUniqueId());limits.remove(e.getPlayer().getUniqueId());}
 @Override public void close(){closing=true;Bukkit.getServicesManager().unregister(ShopBridge.class,this);io.shutdown();try{if(io.awaitTermination(10,TimeUnit.SECONDS))store.close();}catch(Exception e){Thread.currentThread().interrupt();}sessions.clear();}
}
