package school.magiccodex.paper;
import java.math.BigDecimal;import java.nio.file.Path;import java.sql.*;import java.util.*;
import school.magiccodex.database.*;
final class ShopStore implements AutoCloseable {
 record Product(String id,String name,byte[] bytes,String buy,String sell){}
 record Shop(String id,String title,String portrait,long revision,List<Product> products){}
 record Order(String id,UUID owner,String state,String mode,String product,int quantity,String total,byte[] bytes,String title){}
 private final ConnectionHolder holder;private final String shops,products,orders,bindings,version;
 ShopStore(DatabaseSettings settings,Path path)throws Exception{holder=settings.holder(path);shops=settings.table("shops","shops");products=settings.table("shop_products","shop_products");orders=settings.table("shop_orders","shop_orders");bindings=settings.table("shop_bindings","shop_bindings");version=settings.table("shop_version","shop_version");String tail=settings.mariaDb()?" ENGINE=InnoDB DEFAULT CHARSET=utf8mb4":"";try(var s=db().createStatement()){
 s.execute("CREATE TABLE IF NOT EXISTS "+shops+"(id VARCHAR(48) PRIMARY KEY,title VARCHAR(80) NOT NULL,portrait VARCHAR(120) NOT NULL,revision BIGINT NOT NULL)"+tail);
 s.execute("CREATE TABLE IF NOT EXISTS "+products+"(id VARCHAR(36) PRIMARY KEY,shop VARCHAR(48) NOT NULL,name VARCHAR(120) NOT NULL,payload BLOB NOT NULL,buy VARCHAR(32) NOT NULL,sell VARCHAR(32) NOT NULL)"+tail);
 s.execute("CREATE TABLE IF NOT EXISTS "+orders+"(id VARCHAR(36) PRIMARY KEY,owner VARCHAR(36) NOT NULL,request_key VARCHAR(36) NOT NULL UNIQUE,state VARCHAR(20) NOT NULL,mode VARCHAR(8) NOT NULL,product VARCHAR(36) NOT NULL,quantity INTEGER NOT NULL,total VARCHAR(32) NOT NULL,payload BLOB NOT NULL,title VARCHAR(80) NOT NULL,created BIGINT NOT NULL)"+tail);
 s.execute("CREATE TABLE IF NOT EXISTS "+bindings+"(origin VARCHAR(36) NOT NULL,npc VARCHAR(80) NOT NULL,shop VARCHAR(48) NOT NULL,PRIMARY KEY(origin,npc))"+tail);
 s.execute("CREATE TABLE IF NOT EXISTS "+version+"(id INTEGER PRIMARY KEY,revision BIGINT NOT NULL)"+tail);
 }try(var s=db().prepareStatement("INSERT INTO "+version+"(id,revision) VALUES(1,0)")){try{s.executeUpdate();}catch(SQLException e){if(e.getErrorCode()!=19&&e.getErrorCode()!=1062)throw e;}}}
 private Connection db()throws SQLException{return holder.get();}private interface Work<T>{T run()throws Exception;}
 private <T>T tx(Work<T> work)throws Exception{var c=holder.begin();try{try(var s=c.createStatement()){s.executeUpdate("UPDATE "+version+" SET revision=revision+1 WHERE id=1");}T out=work.run();c.commit();return out;}catch(Exception e){holder.rollback();throw e;}finally{holder.end();}}
 static String price(String value){if(value.equalsIgnoreCase("off"))return "";var p=new BigDecimal(value);if(p.signum()<0||p.compareTo(new BigDecimal("1000000000000"))>0||p.scale()>6)throw new IllegalArgumentException("가격은 0 이상, 소수점 6자리 이하로 입력하세요.");return p.stripTrailingZeros().toPlainString();}
 long version()throws SQLException{try(var s=db().createStatement();var r=s.executeQuery("SELECT revision FROM "+version+" WHERE id=1")){r.next();return r.getLong(1);}}
 Map<String,Shop> catalog()throws SQLException{var out=new HashMap<String,Shop>();try(var s=db().createStatement();var r=s.executeQuery("SELECT id,title,portrait,revision FROM "+shops+" ORDER BY id")){while(r.next()){String id=r.getString(1);var list=new ArrayList<Product>();try(var p=db().prepareStatement("SELECT id,name,payload,buy,sell FROM "+products+" WHERE shop=? ORDER BY name,id")){p.setString(1,id);try(var q=p.executeQuery()){while(q.next())list.add(new Product(q.getString(1),q.getString(2),q.getBytes(3),q.getString(4),q.getString(5)));}}out.put(id,new Shop(id,r.getString(2),r.getString(3),r.getLong(4),List.copyOf(list)));}}return Map.copyOf(out);}
 Map<String,String> bindings(String origin)throws SQLException{var out=new HashMap<String,String>();try(var s=db().prepareStatement("SELECT npc,shop FROM "+bindings+" WHERE origin=?")){s.setString(1,origin);try(var r=s.executeQuery()){while(r.next())out.put(r.getString(1),r.getString(2));}}return Map.copyOf(out);}
 void create(String id,String title)throws Exception{if(!id.matches("[a-z0-9_-]{1,48}")||title.isBlank()||title.length()>80)throw new IllegalArgumentException("상점 ID/이름을 확인하세요.");tx(()->{try(var s=db().prepareStatement("INSERT INTO "+shops+"(id,title,portrait,revision) VALUES(?,?,'elena-neutral',1)")){s.setString(1,id);s.setString(2,title);s.executeUpdate();}return null;});}
 private void bump(String shop)throws SQLException{try(var s=db().prepareStatement("UPDATE "+shops+" SET revision=revision+1 WHERE id=?")){s.setString(1,shop);if(s.executeUpdate()!=1)throw new IllegalArgumentException("상점 없음");}}
 String add(String shop,String name,byte[] payload,String buy,String sell)throws Exception{return tx(()->{bump(shop);String id=UUID.randomUUID().toString();try(var s=db().prepareStatement("INSERT INTO "+products+"(id,shop,name,payload,buy,sell) VALUES(?,?,?,?,?,?)")){s.setString(1,id);s.setString(2,shop);s.setString(3,name);s.setBytes(4,payload);s.setString(5,buy);s.setString(6,sell);s.executeUpdate();}return id;});}
 void prices(String shop,String id,String buy,String sell)throws Exception{tx(()->{bump(shop);try(var s=db().prepareStatement("UPDATE "+products+" SET buy=?,sell=? WHERE shop=? AND id=?")){s.setString(1,buy);s.setString(2,sell);s.setString(3,shop);s.setString(4,id);if(s.executeUpdate()!=1)throw new IllegalArgumentException("상품 없음");}return null;});}
 void portrait(String shop,String portrait)throws Exception{if(!portrait.matches("[a-z0-9_/-]{1,120}")||portrait.contains(".."))throw new IllegalArgumentException("초상 ID");tx(()->{bump(shop);try(var s=db().prepareStatement("UPDATE "+shops+" SET portrait=? WHERE id=?")){s.setString(1,portrait);s.setString(2,shop);s.executeUpdate();}return null;});}
 void bind(String origin,String npc,String shop)throws Exception{if(!npc.matches("citizens:[0-9]{1,9}|tag:[a-zA-Z0-9_-]{1,64}"))throw new IllegalArgumentException("NPC 연결키");tx(()->{bump(shop);try(var s=db().prepareStatement("DELETE FROM "+bindings+" WHERE origin=? AND npc=?")){s.setString(1,origin);s.setString(2,npc);s.executeUpdate();}try(var s=db().prepareStatement("INSERT INTO "+bindings+"(origin,npc,shop) VALUES(?,?,?)")){s.setString(1,origin);s.setString(2,npc);s.setString(3,shop);s.executeUpdate();}return null;});}

 /** The shared version row is locked by tx before this comparison. */
 private void adminRevision(String shop,long expected)throws SQLException{try(var s=db().prepareStatement("SELECT revision FROM "+shops+" WHERE id=?")){s.setString(1,shop);try(var q=s.executeQuery()){if(!q.next())throw new IllegalArgumentException("상점 없음");if(q.getLong(1)!=expected)throw new IllegalStateException("다른 관리자가 상품을 변경했습니다. 새로고침 후 다시 확인하세요.");}}}
 private static void adminValues(String name,byte[] payload,String buy,String sell){if(name.isBlank()||name.length()>120||name.codePoints().anyMatch(Character::isISOControl))throw new IllegalArgumentException("상품 이름 확인");if(payload==null||payload.length<1||payload.length>32768)throw new IllegalArgumentException("아이템 데이터 크기 확인");for(String v:List.of(buy,sell))if(!v.isEmpty()&&!price(v).equals(v))throw new IllegalArgumentException("가격 확인");}
 String adminAdd(String shop,long expected,String name,byte[] payload,String buy,String sell)throws Exception{adminValues(name,payload,buy,sell);return tx(()->{adminRevision(shop,expected);bump(shop);String id=UUID.randomUUID().toString();try(var s=db().prepareStatement("INSERT INTO "+products+"(id,shop,name,payload,buy,sell) VALUES(?,?,?,?,?,?)")){s.setString(1,id);s.setString(2,shop);s.setString(3,name);s.setBytes(4,payload);s.setString(5,buy);s.setString(6,sell);s.executeUpdate();}return id;});}
 void adminEdit(String shop,long expected,String id,String name,String buy,String sell)throws Exception{adminValues(name,new byte[]{1},buy,sell);tx(()->{adminRevision(shop,expected);try(var s=db().prepareStatement("UPDATE "+products+" SET name=?,buy=?,sell=? WHERE shop=? AND id=?")){s.setString(1,name);s.setString(2,buy);s.setString(3,sell);s.setString(4,shop);s.setString(5,id);if(s.executeUpdate()!=1)throw new IllegalArgumentException("상품 없음");}bump(shop);return null;});}
 void adminDelete(String shop,long expected,String id)throws Exception{tx(()->{adminRevision(shop,expected);try(var s=db().prepareStatement("DELETE FROM "+products+" WHERE shop=? AND id=?")){s.setString(1,shop);s.setString(2,id);if(s.executeUpdate()!=1)throw new IllegalArgumentException("상품 없음");}bump(shop);return null;});}
 Order prepare(UUID owner,String request,String shop,long revision,String product,int quantity,boolean selling)throws Exception{return tx(()->{
  if(quantity<1||quantity>576)throw new IllegalArgumentException("수량 한도");
  try(var s=db().prepareStatement("SELECT id FROM "+orders+" WHERE request_key=?")){s.setString(1,request);try(var r=s.executeQuery()){if(r.next())throw new IllegalStateException("이미 처리한 요청입니다. 우편/인벤토리를 확인해 주세요.");}}
  try(var s=db().prepareStatement("SELECT id FROM "+orders+" WHERE owner=? AND state NOT IN ('done','failed')")){s.setString(1,owner.toString());try(var r=s.executeQuery()){if(r.next())throw new IllegalStateException("이전 거래 기록 확인이 필요합니다.");}}
  Shop current=catalog().get(shop);if(current==null||current.revision!=revision)throw new IllegalStateException("상점 설정이 변경되었습니다. 다시 열어 주세요.");Product p=current.products.stream().filter(x->x.id.equals(product)).findFirst().orElseThrow();String unit=selling?p.sell:p.buy;if(unit.isEmpty())throw new IllegalStateException("허용하지 않는 거래입니다.");BigDecimal total=new BigDecimal(unit).multiply(BigDecimal.valueOf(quantity));if(total.compareTo(new BigDecimal("1000000000000"))>0)throw new IllegalArgumentException("합계 한도 초과");String id=UUID.randomUUID().toString();Order o=new Order(id,owner,"prepared",selling?"sell":"buy",product,quantity,total.toPlainString(),p.bytes,current.title);
  try(var s=db().prepareStatement("INSERT INTO "+orders+"(id,owner,request_key,state,mode,product,quantity,total,payload,title,created) VALUES(?,?,?,'prepared',?,?,?,?,?,?,?)")){s.setString(1,id);s.setString(2,owner.toString());s.setString(3,request);s.setString(4,o.mode);s.setString(5,product);s.setInt(6,quantity);s.setString(7,o.total);s.setBytes(8,p.bytes);s.setString(9,current.title);s.setLong(10,System.currentTimeMillis());s.executeUpdate();}return o;
 });}
 void state(String id,String expected,String next)throws Exception{tx(()->{try(var s=db().prepareStatement("UPDATE "+orders+" SET state=? WHERE id=? AND state=?")){s.setString(1,next);s.setString(2,id);s.setString(3,expected);if(s.executeUpdate()!=1)throw new IllegalStateException("거래 상태 변경");}return null;});}
 List<Order> paid(UUID owner)throws SQLException{var out=new ArrayList<Order>();try(var s=db().prepareStatement("SELECT id,state,mode,product,quantity,total,payload,title FROM "+orders+" WHERE owner=? AND state='paid' AND mode='buy'")){s.setString(1,owner.toString());try(var r=s.executeQuery()){while(r.next())out.add(new Order(r.getString(1),owner,r.getString(2),r.getString(3),r.getString(4),r.getInt(5),r.getString(6),r.getBytes(7),r.getString(8)));}}return out;}
 List<String> audit(UUID owner)throws SQLException{var out=new ArrayList<String>();try(var s=db().prepareStatement("SELECT id,state,mode,quantity,total FROM "+orders+" WHERE owner=? AND state NOT IN ('done','failed') ORDER BY created")){s.setString(1,owner.toString());try(var r=s.executeQuery()){while(r.next())out.add(r.getString(1)+" "+r.getString(2)+" "+r.getString(3)+" qty="+r.getInt(4)+" total="+r.getString(5));}}return out;}
 @Override public void close()throws Exception{holder.close();}
}
